--CREATE or replace VIEW InFlight_Notes AS 
SELECT 
AGREE_ID, 
AGREE_NUM, 
AGR_NUM, 
AGREE_DT, 
AGREE_STATUS, 
AGR_NOTE_CREATED, 
AGR_NOTE_CREATED_BY, 
    CASE 
    WHEN LENGTH(AGR_NOTE_CREATED_BY) < 8 THEN LPAD(AGR_NOTE_CREATED_BY,8,'0')
    WHEN AGR_NOTE_CREATED_BY LIKE 'A%' THEN LTRIM(AGR_NOTE_CREATED_BY, 'A')
    ELSE AGR_NOTE_CREATED_BY
    END new_NOTE_CREATED_BY,
AGR_NOTE_TYPE, 
AGR_NOTE_DESC 
FROM INTFUSER.TMP_QUT_AGR_NOTE_DETAILS;
