/* 
	Who	When	What
    	==========================================================================================
	KB	MMDD22	Initial view created
	JZ	121222	Formatted view and added header information for tracking changes
	CM	011823	Adding AGR_INT_COMMENTS
	KB  	013023  Combined Siebel and Oracle tables with conditions
	CM	020223	Added ISG_Duration - ALSO USING OLD TABLE INTFUSER.TMP_AGR_DATA_PRD_ACT_23
	CM	021423	Reverted back to original table INTFUSER.TMP_AGR_DATA_PRD_ACT for Mock2
	KB  040123  Added Tax codes in the view.
  CM  041823  Adding AGR_LINE_INT_COMMENTS
*/

-- Need to check view for Cartesian join causing duplication
-- Comment out Create line when testing to not blow away your working view
--CREATE or replace VIEW SIEBEL_QT_Line AS
SELECT
T1.AGREE_ID,
T1.AGR_NUM,
T1.AGR_NAME,
T1.AGR_OPP_ID,
T1.AGREE_STATUS,
T1.AGREE_SUB_STATUS,
T1.ora_ord_num,
T1.BILL_TO_ADDR_SITE,
T1.SHIP_TO_ADDR_SITE,
T1.AGR_START_DT,
T1.AGR_END_DT,
T1.CURRENCY,
T1.AGR_BILL_TYPE,
T1.AGR_BILL_FREQ,
T1.AGR_ACCT_AUTH,
T1.AGREE_TYPE,
T1.AGREE_SALES_REP_CD,
T1.AGR_LINE_ID,
T1.AGR_LINE_STATUS,
T1.ASSET_NUM,
T1.ASSET_SF_ID,
T1.QTY_REQ,
T1.AGR_LINE_START_DT,
T1.AGR_LINE_END_DT,
CASE 
		WHEN AGR_BUS_UNIT = 'ISG' THEN ROUND(MONTHS_BETWEEN(AGR_LINE_END_DT, AGR_LINE_START_DT),4) 
		ELSE null
  END AS ISG_Duration,
T1.MONTH_PRICE,
T1.ADJ_UNIT_PRI,
T1.LINE_SPN,
T1.INT_MODEL,
T1.AGR_LINE_COMMENTS,
T1.AGR_BUS_UNIT,
T1.AGR_INT_COMMENTS,
T1.AGR_LINE_INT_COMMENTS,
T2.AGREE_ID AS Oracle_AGREE_ID, 
T2.AGR_NUM AS Oracle_AGR_NUM,
T2.ORA_AGR_ID AS Oracle_ORA_AGR_ID ,
T2.AGR_LINE_ID AS Oracle_AGR_LINE_ID ,
T2.AGR_REVISION AS Oracle_AGR_REVISION ,
T2.ORDER_STATUS AS Oracle_ORDER_STATUS ,
T2.ORACLE_LINE_ID AS Oracle_LINE_ID,
T2.LINE_NUMBER AS Oracle_LINE_NUMBER ,
T2.SPN AS Oracle_SPN ,
T2.ITEM_SERVICED AS Oracle_ITEM_SERVICED,
T2.DURATION_MONTHS AS Oracle_DURATION_MONTHS ,
T2.BILL_DAY_OF_THE_MONTH AS Oracle_BILL_DAY_OF_THE_MONTH ,
T2.NEXT_BILLING_DATE AS Oracle_NEXT_BILLING_DATE ,
T2.DURATION AS Oracle_DURATION ,
T2.BILLING_FREQUENCY AS Oracle_BILLING_FREQUENCY,
T2.COMMENTS AS Oracle_COMMENTS,
T2.INVOICE_AMT AS Oracle_INVOICE_AMT,
T2.TAX_ITEM_CATEGORY AS Oracle_TAX_ITEM_CATEGORY,
T2.SUBSCRIPTION_ID AS Oracle_SUBSCRIPTION_ID,
T2.EB_TAX_CODE,
T2.SABRIX_TAX_CODE
FROM 
INTFUSER.TMP_AGR_DATA_PRD_ACT T1
LEFT JOIN
INTFUSER.XXKT_SIEBEL_ELIG_ORD_MIG T2
ON T1.AGR_LINE_ID = T2.AGR_LINE_ID 
AND T2.LINE_NUMBER IS NOT NULL
AND T2.DURATION != 0
AND (T2.BILLING_FREQUENCY IS NOT NULL OR T2.BILLING_FREQUENCY NOT LIKE 'N/A');