/* 
	Who	When	What
    	==========================================================================================
	JZ	120922	Initial view created
	JZ	121222	Updated logic to account for additional discounts
					Added Discount_Method to allow for multiple discount types
					Added header information for tracking changes
	JZ	121322	Updated Sort order with case to push Surcharges to the top
	JZ	121422	Updated CASE at end to account for Surcharge5 which was missing from logic
	JZ	121522	Updated logic to better comebine the lines together in preparation for the second layer
	JZ	121622	Added missing IS_SURCHARGE logic for additional modifiers as they have downstream impact
*/
-- Need to check view for Cartesian join causing duplication
-- Comment out Create line when testing to not blow away your working view
-- CREATE OR REPLACE VIEW Siebel_Discounts_Combined_v AS
WITH CTE_1 AS 
(
SELECT 
	-- DENSE_RANK () OVER (PARTITION BY AGR_LINE_ID_DISCOUNTS ORDER BY AGR_LINE_ID_DISCOUNTS, "Modifier_1", "Modifier_2", "Modifier_3" , "Modifier_4" , "Modifier_5") AS RANK_X,
	RN, CASE 
		WHEN (DISCOUNT_METHOD = 'Percent' AND AGR_MOD_PERCENT > 0.0) THEN 'Uplift'
		ELSE DISCOUNT_METHOD 
	END AS "DISC_METHOD",
	CASE 
		WHEN (DISCOUNT_METHOD = 'Percent' AND AGR_MOD_PERCENT > 0.0) THEN 'Y'
		ELSE 'N'
	END AS "IS_SURCHARGE",
	Discount_Method, AGREE_ID_DISCOUNTS, AGREE_NUM_DISCOUNTS, AGREE_STATUS_DISCOUNTS, AGR_LINE_ID_DISCOUNTS, AGR_MOD_ID, AGR_MOD_DESC,  AGR_MOD_PERCENT, AGR_MOD_AMT
FROM SIEBEL_QUOTE_LINE_DIS
WHERE IS_SURCHARGE = 'N'
-- WHERE  AGR_LINE_ID_DISCOUNTS = '1-6JZSGED'
-- WHERE (AGR_MOD_PERCENT > '0.0' AND DISCOUNT_METHOD = 'Percent')
)

SELECT 
	D1.IS_SURCHARGE AS IS_SURCHARGE_1,
	D1.AGR_LINE_ID_DISCOUNTS AS AGR_LINE_ID_DISCOUNTS_1,
	D1.AGR_MOD_ID AS AGR_MOD_ID_1,
	CASE 
		WHEN D1.IS_SURCHARGE != 'Y' THEN NULL
		ELSE D1.DISC_METHOD 
	END AS "Surcharge_Method_1",
	CASE
		WHEN D1.IS_SURCHARGE != 'Y' THEN NULL 
		ELSE D1.AGR_MOD_PERCENT 
	END AS "Surcharge_Total_1",
	CASE 
		WHEN D1.IS_SURCHARGE = 'Y' THEN NULL 
		ELSE D1.AGR_MOD_DESC
	END AS "AGR_MOD_DESC_1",
	CASE 
		WHEN D1.IS_SURCHARGE = 'Y' THEN NULL
		ELSE D1.DISC_METHOD 
	END AS "DISC_METHOD_1",
	CASE
		WHEN D1.IS_SURCHARGE = 'Y' THEN NULL 
		WHEN D1.AGR_MOD_PERCENT IS NOT NULL THEN D1.AGR_MOD_PERCENT
		ELSE D1.AGR_MOD_AMT
	END AS "Discount_1",
	D2.IS_SURCHARGE AS IS_SURCHARGE_2,
	CASE 
		WHEN D2.IS_SURCHARGE != 'Y' THEN NULL
		ELSE D2.DISC_METHOD 
	END AS "Surcharge_Method_2",
	CASE
		WHEN D2.IS_SURCHARGE != 'Y' THEN NULL 
		ELSE D2.AGR_MOD_PERCENT 
	END AS "Surcharge_Total_2",
	CASE 
		WHEN D2.IS_SURCHARGE = 'Y' THEN NULL 
		ELSE D2.AGR_MOD_DESC
	END AS "AGR_MOD_DESC_2",
	CASE 
		WHEN D2.IS_SURCHARGE = 'Y' THEN NULL
		ELSE D2.DISC_METHOD 
	END AS "DISC_METHOD_2",
	CASE
		WHEN D2.IS_SURCHARGE = 'Y' THEN NULL 
		WHEN D2.AGR_MOD_PERCENT IS NOT NULL THEN D2.AGR_MOD_PERCENT
		ELSE D2.AGR_MOD_AMT
	END AS "Discount_2",
	D3.IS_SURCHARGE AS IS_SURCHARGE_3,
	CASE 
		WHEN D3.IS_SURCHARGE != 'Y' THEN NULL
		ELSE D3.DISC_METHOD 
	END AS "Surcharge_Method_3",
	CASE
		WHEN D3.IS_SURCHARGE != 'Y' THEN NULL 
		ELSE D3.AGR_MOD_PERCENT 
	END AS "Surcharge_Total_3",
	CASE 
		WHEN D3.IS_SURCHARGE = 'Y' THEN NULL 
		ELSE D3.AGR_MOD_DESC
	END AS "AGR_MOD_DESC_3",
	CASE 
		WHEN D3.IS_SURCHARGE = 'Y' THEN NULL
		ELSE D3.DISC_METHOD 
	END AS "DISC_METHOD_3",
	CASE
		WHEN D3.IS_SURCHARGE = 'Y' THEN NULL 
		WHEN D3.AGR_MOD_PERCENT IS NOT NULL THEN D3.AGR_MOD_PERCENT
		ELSE D3.AGR_MOD_AMT
	END AS "Discount_3",
	D4.IS_SURCHARGE AS IS_SURCHARGE_4,
	CASE 
		WHEN D4.IS_SURCHARGE != 'Y' THEN NULL
		ELSE D4.DISC_METHOD 
	END AS "Surcharge_Method_4",
	CASE
		WHEN D4.IS_SURCHARGE != 'Y' THEN NULL 
		ELSE D4.AGR_MOD_PERCENT 
	END AS "Surcharge_Total_4",
	CASE 
		WHEN D4.IS_SURCHARGE = 'Y' THEN NULL 
		ELSE D4.AGR_MOD_DESC
	END AS "AGR_MOD_DESC_4",
	CASE 
		WHEN D4.IS_SURCHARGE = 'Y' THEN NULL
		ELSE D4.DISC_METHOD 
	END AS "DISC_METHOD_4",
	CASE
		WHEN D4.IS_SURCHARGE = 'Y' THEN NULL 
		WHEN D4.AGR_MOD_PERCENT IS NOT NULL THEN D4.AGR_MOD_PERCENT
		ELSE D4.AGR_MOD_AMT
	END AS "Discount_4",
	D5.IS_SURCHARGE AS IS_SURCHARGE_5,
	CASE 
		WHEN D5.IS_SURCHARGE != 'Y' THEN NULL
		ELSE D5.DISC_METHOD 
	END AS "Surcharge_Method_5",
	CASE
		WHEN D5.IS_SURCHARGE != 'Y' THEN NULL 
		ELSE D5.AGR_MOD_PERCENT 
	END AS "Surcharge_Total_5",
	CASE 
		WHEN D5.IS_SURCHARGE = 'Y' THEN NULL 
		ELSE D5.AGR_MOD_DESC
	END AS "AGR_MOD_DESC_5",
	CASE 
		WHEN D5.IS_SURCHARGE = 'Y' THEN NULL
		ELSE D5.DISC_METHOD 
	END AS "DISC_METHOD_5",
	CASE
		WHEN D5.IS_SURCHARGE = 'Y' THEN NULL 
		WHEN D5.AGR_MOD_PERCENT IS NOT NULL THEN D5.AGR_MOD_PERCENT
		ELSE D5.AGR_MOD_AMT
	END AS "Discount_5"
FROM CTE_1 D1 

-- Join the second discount to the first
LEFT JOIN 
	(
		SELECT IS_SURCHARGE, AGR_LINE_ID_DISCOUNTS, AGR_MOD_ID, DISC_METHOD, AGR_MOD_DESC, AGR_MOD_PERCENT, AGR_MOD_AMT 
  		FROM CTE_1
		WHERE RN = 2
	) D2
		ON (D2.AGR_LINE_ID_DISCOUNTS = D1.AGR_LINE_ID_DISCOUNTS)

-- Join the third discount back to the first two
LEFT JOIN 
	(
		SELECT IS_SURCHARGE, AGR_LINE_ID_DISCOUNTS, AGR_MOD_ID, DISC_METHOD, AGR_MOD_DESC, AGR_MOD_PERCENT, AGR_MOD_AMT 
		FROM CTE_1
		WHERE RN = 3
	) D3
		ON (D3.AGR_LINE_ID_DISCOUNTS = D1.AGR_LINE_ID_DISCOUNTS)

-- Join the fourth discount back to the first three
LEFT JOIN 
	(
		SELECT IS_SURCHARGE, AGR_LINE_ID_DISCOUNTS, AGR_MOD_ID, DISC_METHOD, AGR_MOD_DESC, AGR_MOD_PERCENT, AGR_MOD_AMT 
  		FROM CTE_1
		WHERE RN = 4
	) D4
		ON (D4.AGR_LINE_ID_DISCOUNTS = D1.AGR_LINE_ID_DISCOUNTS)
		
-- Join the fifth discount back to the first four
LEFT JOIN 
	(
		SELECT IS_SURCHARGE, AGR_LINE_ID_DISCOUNTS, AGR_MOD_ID, DISC_METHOD, AGR_MOD_DESC, AGR_MOD_PERCENT, AGR_MOD_AMT 
  		FROM CTE_1
		WHERE RN = 5
	) D5
		ON (D5.AGR_LINE_ID_DISCOUNTS = D1.AGR_LINE_ID_DISCOUNTS)
		
 WHERE RN = 1
 AND D1.IS_SURGHARGE = 'N' AND D2.IS_SURCHARGE = 'N'



